# Generated by Django 4.1 on 2022-10-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuration", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceParameterScore",
            fields=[
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="configuration.channelsourceparameter",
                    ),
                ),
                (
                    "parameter_score",
                    models.FloatField(default=0.0, verbose_name="Parameter Score"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelTypeParameterScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_score",
                    models.FloatField(default=0.0, verbose_name="Parameter Score"),
                ),
                (
                    "channel_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter",
                        to="configuration.channeltypeparameter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelParameterScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_score",
                    models.FloatField(default=0.0, verbose_name="Parameter scores"),
                ),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter",
                        to="configuration.channelparameter",
                    ),
                ),
            ],
        ),
    ]
